"""añado delete cascade para trip

Revision ID: 045197714b87
Revises: a6993f27ca05
Create Date: 2025-03-11 19:48:18.682443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045197714b87'
down_revision: Union[str, None] = 'a6993f27ca05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trip_ibfk_2', 'trip', type_='foreignkey')
    op.create_foreign_key(None, 'trip', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.create_foreign_key('trip_ibfk_2', 'trip', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
