"""user_conection on delete cascade

Revision ID: 3e780905d636
Revises: ab72483c91bb
Create Date: 2025-03-30 10:05:53.842042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e780905d636'
down_revision: Union[str, None] = 'ab72483c91bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_connection_ibfk_2', 'user_connection', type_='foreignkey')
    op.drop_constraint('user_connection_ibfk_1', 'user_connection', type_='foreignkey')
    op.create_foreign_key(None, 'user_connection', 'user', ['user_id_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_connection', 'user', ['user_id_1'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_connection', type_='foreignkey')
    op.drop_constraint(None, 'user_connection', type_='foreignkey')
    op.create_foreign_key('user_connection_ibfk_1', 'user_connection', 'user', ['user_id_1'], ['id'])
    op.create_foreign_key('user_connection_ibfk_2', 'user_connection', 'user', ['user_id_2'], ['id'])
    # ### end Alembic commands ###
