"""make_code_larger

Revision ID: 58efc8926e84
Revises: 70ba663e8e89
Create Date: 2025-03-03 19:46:25.594105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '58efc8926e84'
down_revision: Union[str, None] = '70ba663e8e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_reset_codes', 'code',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_reset_codes', 'code',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
