"""ondelete cascade para trip_category

Revision ID: 5ea56be99d7c
Revises: ca0e869b0d7a
Create Date: 2025-03-15 16:55:36.765782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea56be99d7c'
down_revision: Union[str, None] = 'ca0e869b0d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trip_ibfk_2', 'trip', type_='foreignkey')
    op.create_foreign_key(None, 'trip', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('trip_category_ibfk_2', 'trip_category', type_='foreignkey')
    op.create_foreign_key(None, 'trip_category', 'trip', ['trip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip_category', type_='foreignkey')
    op.create_foreign_key('trip_category_ibfk_2', 'trip_category', 'trip', ['trip_id'], ['id'])
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.create_foreign_key('trip_ibfk_2', 'trip', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
