"""Crear db

Revision ID: 7d07c3d65c66
Revises: 
Create Date: 2025-02-04 18:48:01.556620

"""
from typing import Sequence, Union
from sqlalchemy import func
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7d07c3d65c66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destination',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True,server_default=func.now()),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True,server_default=func.now(), onupdate=func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('auth_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=func.now()),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True,server_default=func.now(), onupdate=func.now()),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub')
    )
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('short_description', sa.String(length=100), nullable=False),
    sa.Column('long_description', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=func.now()),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True,server_default=func.now(), onupdate=func.now()),
    sa.Column('latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('longitude', sa.Float(asdecimal=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_category_id'), 'challenge', ['category_id'], unique=False)
    op.create_index(op.f('ix_challenge_destination_id'), 'challenge', ['destination_id'], unique=False)
    op.create_table('trip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=False, server_default=func.now()),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=False, server_default=func.now()),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=func.now()),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_destination_id'), 'trip', ['destination_id'], unique=False)
    op.create_index(op.f('ix_trip_user_id'), 'trip', ['user_id'], unique=False)
    op.create_table('completed_challenge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True, server_default=func.now()),
    sa.Column('proof_photo_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completed_challenge_challenge_id'), 'completed_challenge', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_completed_challenge_trip_id'), 'completed_challenge', ['trip_id'], unique=False)
    op.create_index(op.f('ix_completed_challenge_user_id'), 'completed_challenge', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_completed_challenge_user_id'), table_name='completed_challenge')
    op.drop_index(op.f('ix_completed_challenge_trip_id'), table_name='completed_challenge')
    op.drop_index(op.f('ix_completed_challenge_challenge_id'), table_name='completed_challenge')
    op.drop_table('completed_challenge')
    op.drop_index(op.f('ix_trip_user_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_destination_id'), table_name='trip')
    op.drop_table('trip')
    op.drop_index(op.f('ix_challenge_destination_id'), table_name='challenge')
    op.drop_index(op.f('ix_challenge_category_id'), table_name='challenge')
    op.drop_table('challenge')
    op.drop_table('user')
    op.drop_table('destination')
    op.drop_table('category')
    # ### end Alembic commands ###
