"""Cambiar clave foranea confirmation code

Revision ID: 8ff18d90c462
Revises: b3ad54a5910b
Create Date: 2025-03-04 22:01:09.221396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff18d90c462'
down_revision: Union[str, None] = 'b3ad54a5910b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
