"""all foreign keys with delete cascade

Revision ID: a1fd5762f8f1
Revises: 3e780905d636
Create Date: 2025-03-30 10:17:01.517736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1fd5762f8f1'
down_revision: Union[str, None] = '3e780905d636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('challenge_ibfk_1', 'challenge', type_='foreignkey')
    op.drop_constraint('challenge_ibfk_2', 'challenge', type_='foreignkey')
    op.create_foreign_key(None, 'challenge', 'destination', ['destination_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'challenge', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('completed_challenge_ibfk_2', 'completed_challenge', type_='foreignkey')
    op.drop_constraint('completed_challenge_ibfk_3', 'completed_challenge', type_='foreignkey')
    op.drop_constraint('completed_challenge_ibfk_1', 'completed_challenge', type_='foreignkey')
    op.create_foreign_key(None, 'completed_challenge', 'trip', ['trip_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'completed_challenge', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'completed_challenge', 'challenge', ['challenge_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('trip_ibfk_1', 'trip', type_='foreignkey')
    op.create_foreign_key(None, 'trip', 'destination', ['destination_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('trip_challenge_ibfk_1', 'trip_challenge', type_='foreignkey')
    op.drop_constraint('trip_challenge_ibfk_2', 'trip_challenge', type_='foreignkey')
    op.create_foreign_key(None, 'trip_challenge', 'challenge', ['challenge_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'trip_challenge', 'trip', ['trip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip_challenge', type_='foreignkey')
    op.drop_constraint(None, 'trip_challenge', type_='foreignkey')
    op.create_foreign_key('trip_challenge_ibfk_2', 'trip_challenge', 'trip', ['trip_id'], ['id'])
    op.create_foreign_key('trip_challenge_ibfk_1', 'trip_challenge', 'challenge', ['challenge_id'], ['id'])
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.create_foreign_key('trip_ibfk_1', 'trip', 'destination', ['destination_id'], ['id'])
    op.drop_constraint(None, 'completed_challenge', type_='foreignkey')
    op.drop_constraint(None, 'completed_challenge', type_='foreignkey')
    op.drop_constraint(None, 'completed_challenge', type_='foreignkey')
    op.create_foreign_key('completed_challenge_ibfk_1', 'completed_challenge', 'challenge', ['challenge_id'], ['id'])
    op.create_foreign_key('completed_challenge_ibfk_3', 'completed_challenge', 'user', ['user_id'], ['id'])
    op.create_foreign_key('completed_challenge_ibfk_2', 'completed_challenge', 'trip', ['trip_id'], ['id'])
    op.drop_constraint(None, 'challenge', type_='foreignkey')
    op.drop_constraint(None, 'challenge', type_='foreignkey')
    op.create_foreign_key('challenge_ibfk_2', 'challenge', 'destination', ['destination_id'], ['id'])
    op.create_foreign_key('challenge_ibfk_1', 'challenge', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
