"""cambiar confirmation code a eliminar en cascade

Revision ID: b3ad54a5910b
Revises: ba43ffbbd7da
Create Date: 2025-03-04 21:17:35.611067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ad54a5910b'
down_revision: Union[str, None] = 'ba43ffbbd7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('confirmation_codes_ibfk_1', 'confirmation_codes', type_='foreignkey')
    op.create_foreign_key(None, 'confirmation_codes', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'confirmation_codes', type_='foreignkey')
    op.create_foreign_key('confirmation_codes_ibfk_1', 'confirmation_codes', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
